/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIFind */

#ifndef _Included_JNIFind
#define _Included_JNIFind
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIFind
 * Method:    create_search_pool
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_JNIFind_create_1search_1pool
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JNIFind
 * Method:    destroy_search_pool
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_JNIFind_destroy_1search_1pool
  (JNIEnv *, jobject, jlong);

/*
 * Class:     JNIFind
 * Method:    add_one
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_JNIFind_add_1one
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     JNIFind
 * Method:    find_0
 * Signature: ([FJ)I
 */
JNIEXPORT jint JNICALL Java_JNIFind_find_10
  (JNIEnv *, jobject, jfloatArray, jlong);

/*
 * Class:     JNIFind
 * Method:    find_1
 * Signature: ([FJ)I
 */
JNIEXPORT jint JNICALL Java_JNIFind_find_11
  (JNIEnv *, jobject, jfloatArray, jlong);

/*
 * Class:     JNIFind
 * Method:    find_2
 * Signature: ([FJ)I
 */
JNIEXPORT jint JNICALL Java_JNIFind_find_12
  (JNIEnv *, jobject, jfloatArray, jlong);

/*
 * Class:     JNIFind
 * Method:    find_3
 * Signature: ([FJ)I
 */
JNIEXPORT jint JNICALL Java_JNIFind_find_13
  (JNIEnv *, jobject, jfloatArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
